name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker images
      run: |
        # Build frontend
        docker build -t minipos-frontend:latest ./frontend
        docker save minipos-frontend:latest > frontend-image.tar
        
        # Build backend
        docker build -t minipos-backend:latest ./backend
        docker save minipos-backend:latest > backend-image.tar
    
    - name: Transfer Docker images
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: 6401
        username: gepi
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "frontend-image.tar,backend-image.tar"
        target: "/tmp/"
        strip_components: 0
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: 6401
        username: gepi
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Load images
          docker load < /tmp/frontend-image.tar
          docker load < /tmp/backend-image.tar
          
          # Stop existing containers
          docker-compose down || true
          
          # Start new containers
          docker-compose up -d
          
          # Cleanup
          rm /tmp/frontend-image.tar
          rm /tmp/backend-image.tar 