name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SERVER_HOST }}
        if_key_exists: fail
    
    - name: Build Docker images
      run: |
        # Build frontend
        docker build -t minipos-frontend:latest ./frontend
        docker save minipos-frontend:latest > frontend-image.tar
        
        # Build backend
        docker build -t minipos-backend:latest ./backend
        docker save minipos-backend:latest > backend-image.tar
    
    - name: Transfer Docker images
      run: |
        scp -o StrictHostKeyChecking=no -P 6401 frontend-image.tar gepi@${{ secrets.SERVER_HOST }}:/tmp/
        scp -o StrictHostKeyChecking=no -P 6401 backend-image.tar gepi@${{ secrets.SERVER_HOST }}:/tmp/
    
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no -p 6401 gepi@${{ secrets.SERVER_HOST }} '
          # Load images
          docker load < /tmp/frontend-image.tar
          docker load < /tmp/backend-image.tar
          
          # Stop existing containers
          docker-compose down || true
          
          # Start new containers
          docker-compose up -d
          
          # Cleanup
          rm /tmp/frontend-image.tar
          rm /tmp/backend-image.tar
        ' 