name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup SSH
      run: |
        # Create .ssh directory in the workspace
        mkdir -p $GITHUB_WORKSPACE/.ssh
        chmod 700 $GITHUB_WORKSPACE/.ssh
        
        # Write the private key to a file
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $GITHUB_WORKSPACE/.ssh/id_ed25519
        chmod 600 $GITHUB_WORKSPACE/.ssh/id_ed25519
        
        # Add the server to known hosts
        ssh-keyscan -H -p 6401 ${{ secrets.SERVER_HOST }} >> $GITHUB_WORKSPACE/.ssh/known_hosts
        chmod 600 $GITHUB_WORKSPACE/.ssh/known_hosts
        
        # Start ssh-agent and add the key
        eval $(ssh-agent -s)
        ssh-add $GITHUB_WORKSPACE/.ssh/id_ed25519
    
    - name: Build Docker images
      run: |
        # Build frontend
        docker build -t minipos-frontend:latest ./frontend
        docker save minipos-frontend:latest > frontend-image.tar
        
        # Build backend
        docker build -t minipos-backend:latest ./backend
        docker save minipos-backend:latest > backend-image.tar
    
    - name: Transfer Docker images
      run: |
        scp -o StrictHostKeyChecking=no -P 6401 frontend-image.tar gepi@${{ secrets.SERVER_HOST }}:/tmp/
        scp -o StrictHostKeyChecking=no -P 6401 backend-image.tar gepi@${{ secrets.SERVER_HOST }}:/tmp/
    
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no -p 6401 gepi@${{ secrets.SERVER_HOST }} '
          # Load images
          docker load < /tmp/frontend-image.tar
          docker load < /tmp/backend-image.tar
          
          # Stop existing containers
          docker-compose down || true
          
          # Start new containers
          docker-compose up -d
          
          # Cleanup
          rm /tmp/frontend-image.tar
          rm /tmp/backend-image.tar
        ' 