name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: 6401
        username: gepi
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Create deployment directory if it doesn't exist
          mkdir -p /home/gepi/deployments/minipos-cloud
          cd /home/gepi/deployments/minipos-cloud
          
          # Clone or pull the latest code
          if [ -d .git ]; then
            git pull origin main
          else
            git clone https://github.com/eltadmin/minipos-cloud.git .
          fi
          
          # Build and deploy frontend
          cd frontend
          docker build -t minipos-frontend:latest .
          
          # Build and deploy backend
          cd ../backend
          docker build -t minipos-backend:latest .
          
          # Stop existing containers
          cd ..
          docker-compose down || true
          
          # Start new containers
          docker-compose up -d 